version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: microdb
      POSTGRES_USER: microuser
      POSTGRES_PASSWORD: micro123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: django_backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: microdb
      DB_USER: microuser
      DB_PASSWORD: micro123
      DB_HOST: db

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  postgres_data: