apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: projet-systeme-reparti-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              value: microdb
            - name: DB_USER
              value: microuser
            - name: DB_PASSWORD
              value: micro123
            - name: DB_HOST
              value: postgres