---
- name: Déploiement automatique du projet sur Kubernetes
  hosts: local
  become: no

  tasks:

    - name: Vérifier que minikube est démarré
      command: minikube status
      register: minikube_status
      ignore_errors: yes

    - name: Démarrer minikube si nécessaire
      command: minikube start
      when: "'Running' not in minikube_status.stdout"

    - name: Appliquer les manifests Kubernetes
      command: kubectl apply -f ../k8s/